common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data
blocks_storage:
  backend: filesystem
  tsdb:
    dir: /data/tsdb
limits:
  ingestion_rate: 10000
  ingestion_burst_size: 20000
activity_tracker:
  filepath: /active-query-tracker/activity.log
ingester:
  ring:
    zone_awareness_enabled: false
store_gateway:
  sharding_ring:
    zone_awareness_enabled: false
compactor:
  sharding_ring:
    zone_awareness_enabled: false
