# Replicas optimized for 3-worker kind cluster (small homelab)
distributor:
  replicas: 2
ingester:
  replicas: 2
querier:
  replicas: 2
query_frontend:
  replicas: 1
store_gateway:
  replicas: 1
compactor:
  replicas: 1
overrides_exporter:
  replicas: 1
# Gateway (nginx proxy) with LoadBalancer for external access
gateway:
  enabled: true
  service:
    type: LoadBalancer
  nginx:
    basicAuth:
      enabled: false  # Disable for lab; enable with username/password in production
# Enable MinIO for object storage (auto-configured by chart)
minio:
  enabled: true
  mode: standalone
  rootUser: grafana-mimir
  rootPassword: supersecret  # Change in production!
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
# Disable Alertmanager for lab simplicity
alertmanager:
  enabled: false
# Mimir config overrides (minimal for homelab)
mimir:
  structuredConfig:
    multitenancy_enabled: false
    server:
      log_level: info
    # Chart auto-handles S3 config for MinIO
# Disable other optional components for simplicity
ruler:
  enabled: false
continuous_test:
  enabled: false
smoke_test:
  enabled: false
metaMonitoring:
  serviceMonitor:
    enabled: false
  grafanaAgent:
    enabled: false
